version: '3.7'

services:
  app:
    build:
      context: .
    tty: true
    command: modd
    ports:
      - "5000:80"
    volumes:
      - ./:/go/src/app
    env_file:
      - app.env
    environment:
      TZ: Asia/Tokyo
      PORT: 80
      RDS_HOSTNAME: mysql
      RDS_USERNAME: root
      RDS_PASSWORD: pass

  mysql:
    image: mysql:5.7.26
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: muscle_development
      MYSQL_ROOT_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: