version: 2.1

executors:
  default:
    working_directory: ~/muscle-api
    docker:
      - image: circleci/golang:1.12.6-stretch
        environment:
          GO111MODULE: "on"

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - go_mod_download
      - run: go test -v ./...

workflows:
  main:
    jobs:
      - test